name: Generate Documentation
on:
    push:
        tags:
            - "*"
    workflow_dispatch:
        inputs:
            tag:

permissions:
  contents: write

jobs:
    docs:
        name: "Generate and Deploy Documentation"
        uses: GoogleCloudPlatform/php-tools/.github/workflows/doctum.yml@doctum
        with:
          title: "Google Cloud PHP Client"
          default_tag: ${{ inputs.tag }}
          exclude_file: aliases.php
          tag_pattern: "v2.*"

